export const paintings = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418784/Galeria%20R.P%20imagenes%20optimizadas/Oh_amor_no_hay_amor_vn8ddy.png",
    title: "Oh amor, no hay amor",
    detail: "Mixto sobre tela, 90 x 100 cm.",
    think: '"Oh amor, no hay amor" es una idea tomada de la frase atribuida a Aristoteles "oh amigos, no hay amigos" (que en la traducción real sería "quien tiene muchos amigos, no tiene amigos").La obra hace referencia, mas que nada, sobre las construcción social que el ser humano ha hecho en su historia, todo avanza sobre contradicciones. La historia humana desde los primeros tiempos está basada en contradicciones. "Libertad e igualdad", prerrogativas de algunas cartas fundacionales. "Progreso con atraso", lo dicho mas claramente por Benjamin. Y el amor no queda exento de esta contradicción. Hay excepciones a la regla. Amor y posesión. Amor y destrucción. Amor e ilusiones. Amor y engaño. ¿Hasta donde hay amor al otro si mis actos no lo tienen en cuenta?',
    home: true,
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418784/Galeria%20R.P%20imagenes%20optimizadas/La_mirada_de_Clara_jablpy.jpg",
    title: "La mirada (de Clara)",
    detail: "Mixto sobre tela, 90 x 100 cm.",
    think: "No tengo mucho para contar, o sí. La ví, de lejos. Me dí cuenta que era ella. No supe que hacer. Pues ella ni notó ni mi presencia, ni mi existencia. Es difícil, para mí, decidir que hacer en estos casos. Por eso solo guardé la imagen de su mirada cuando abría la puerta de vidrio de ese local y miraba sobre su hombro derecho. Es muy raro sentir y ver, y descubrir la presencia de otra persona que te atrae, que te despierta fantasías, que te genera expectativas, pero vos no exisistis para ella. No te conoce, no sabe de vos. Se que algún día nos conoceremos, nos encontraremos. Quien sabe que va a pasar. Pero seguramente en ese momento las expectativas y las fantasías caerán en la cuenta de la realidad. Habrá seguramente el alivio del saber, del conocer.",
    home: false,
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/La_imagen_de_Clara_twrflq.jpg",
    title: "La imagen de Clara",
    detail: "Mixto sobre tela, 50 x 80 cm.",
    think: 'Cuantas veces vemos en las redes imágenes de gente feliz, con rostros completos, de sonrisas calmas y miradas pacíficas. "Venden" felicidad, paz y tranquilidad a quien las observa. Despertando en el observador el deseo de querer tener una vida así, de poder disfrutar de la vida así como se ve en las fotos. Se despierta una cierta envidia, entendida desde lo mas sano e incluso hasta lo mas dañino de que despierta ese sentimiento. El querer tener una vida así es casi imposible evitar. Salvo las almas mas sanas entienden que la vida de cada uno es como tiene que ser y forzarla a cambiar, para parecerse a otro, es una ridiculez. Porque en definitiva esa imagen es solo una foto de un instante que no representa nada de lo que esa persona vive día a día. Mirar incluso con empatia y deleitarse por ese momento de felicidad y éxito a veces no es la primicia de lo que algunos sienten. La imagen de Clara, muestra que atrás de ella hay fantasmas, como los hay detrás de cada uno de nosotros, los observadores. Las luchas, las frustraciones, la verdad de lo que esconde una simple foto, son las cosas que debemos mirar, y entender que somos testigos de apenas un momento de felicidad, paz, tranquilidad y éxito de esa persona.',
    home: true,
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Te_trajo_el_caos_rbfwlm.png",
    title: "Te trajo el caos",
    detail: "Mixto sobre tela, 40 x 50 cm.",
    think: "Así es como se genera todo, desde el caos, dejando que él actúe, que se exprese, que se desarrolle. La única posibilidad que tiene el artista es estar atento a lo que nace y hacer todo lo posible para que no se escape. Hay que tener paciencia, es casi como la pesca. Más si es en aguas turbias y turbulentas, solo vez la línea y el resto, o lo imaginas o lo percibis. Pero hay que estar atento a no perder la presa en el primer pique. Eso pasa en la pintura, cuando dejas que fluya la mancha, los colores y los trazos. Con la mirada atenta, buscando, girando la tela, tomando distancia para mirar mejor, cambiando los lentes para ver mejor, y seguir con la certeza de que va a aparecer. Y una vez que encontrás la imagen, la asís con fuerza, en tu cabeza, que no se escape, ahí está, no la dejes ir. Luego empezas con la construcción, sin desesperación, si te apuras la perdes. La duda, que siempre me surge, es si esa imagen, la que digo encontrar en el caos, la que creo ver generada en el caos, no está habitando en mi cabeza desde hace mucho tiempo.",
    home: true,
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Lugar_y_Memoria_yu9ae3.jpg",
    title: "Lugar y memoria",
    detail: "Acrílico sobre tela, 60 x 80 cm.",
    think: 'Como nacen las obras o las imágenes de las obras siempre son un misterio. Creo ya haber hablado algo del misterio. No llegas a saber porque está, pero está. Esta imagen nació de tapar otra, de otra época. Es lo que nos pasa a los artistas, por ahí tenes una obra guardada y cuando la vez te preguntas porqué la hiciste, que cosa te pasó por la cabeza, pero ya es "una" extraña, parece que pasaron muchas cosas y esa etapa ya fué. Entonces aprovechas la tela. El blanco existe y es lo mejor que te puede pasar como artista. Pero una vez que arrancas a pintar sobre el blanco y vez que fluye todo la otra imagen, la que quedó abajo, se borra de tu memoria y ni te acordas de que había. Y otra imagen aparece, y empieza a tener una forma muy distinta, claro estás en otra etapa. Pero cuando terminaste y decis "ya no la toco mas, va la firma", y pensas que nombre ponerle, y no encontras el nombre ideal, indicado, aparece de nuevo el misterio de porque la hice. Que me movió a hacerla, que me llevó a diseñar "esa" imagen, que es lo oculto que me hace crearla. Aun para mí no es claro, por tanto un misterio. El proceso es maravilloso. El finalizarla una alegría.',
    home: false,
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/Ella_no_es_Clara_gkfxqp.png",
    title: "Ella no es Clara",
    detail: "Mixto sobre tela, 60 x 80 cm.",
    think: 'Así es, ella no es Clara, no se como se llama, ni donde vive, ni sé donde la encontré. Solo la vi, me pareció que, además de ser bonita, era solitaria. Su mirada estaba dirigida hacia un horizonte mas bien lejano. Pensé que retratarla y ponerla en una de mis obras podría ser motivo que otras personas la puedan ver y también acompañar. Como dije, no conozco su origen, pareciera ser una mujer celta, venida de la antigüedad, pero tiene algo que me lleva a pensar rasgos de modernidad. Es todo un misterio para mí, pero como todo misterio te sorprende, no conoces nada de donde viene pero la sorpresa de su presencia ya habita en el sorprendido. Esa es la esencia del misterio, no es tuyo, te viene dado, como regalo, pero su acción queda en vos. Pasa, por lo tanto a ser tuyo de alguna manera. Ella no es Clara, es un misterio.',
    home: true,
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Clara_en_paralelo_fbbeq2.png",
    title: "Clara en paralelo",
    detail: "Mixto sobre tela, 50 x 70 cm.",
    think: 'Hace unas cuantas semanas atrás al despertar en la mañana y después de haber deambulado unos minutos por mi casa fui hasta el baño y encontré mi imagen frente al espejo. Lo primero que me vino a la cabeza fue "que cansado que estoy de ser yo", luego de ese pensamiento sobrevino un insulto y un sentimiento de angustia. No la estaba pasando muy bien que digamos, seguro algún lector se habrá percatado de ello. Fue un día complicado después de ese pensamiento. Hasta que recordé a Clara y supuse que si ella es mi alma gemela, aún desconocida, podría estar en la misma sintonia que yo. Me la imaginé mirándose al espejo y pensando exactamente lo mismo que yo. "Tiene que ser así", pensé, "si es mi alma gemela, debe sentir lo mismo". En ese momento me empecé a sentir un poco mejor, "no estas mas solo" me dije. "La cuestión es encontrar a Clara". No hablo de cualquier mujer llamada Clara, no, hablo de la Clara que tiene un engemelamiento (si es que existe la palabra) de alma conmigo. Solo espero que ella haya pensado lo mismo que yo pensé, para poder recuperar la esperanza del encuentro de nuestra vidas.',
    home: false,
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Acompa%C3%B1ar_en_un_nuevo_camino_xwqbuv.png",
    title: "Acompañar en un nuevo camino",
    detail: "Mixto sobre tela, 80 x 100 cm.",
    think: 'Hay momentos en la vida que son determinantes, uno de ellos es cuando acompañas en los primeros pasos. La profundidad de estos momentos no es fácilmente percibible, si no estamos atentos no vemos lo profundo de esto. Son los primeros pasos de muchos pasos que marcan un nuevo camino, totalmente distinto a todos los caminos existentes hasta ese momento porque lo empieza a construir alguien nuevo, distinto, con una mirada mas limpia, con un asombro nuevo de la realidad que se le presenta a cada paso. Y el que acompaña es testigo, pero ni está afuera del momento, no es solo un observador de lo que ocurre paso a paso. Si el acompañante está atento puede también aprender a caminar de nuevo, a ver cada paso con el asombro y el estupor de quien recién empieza. Si está atento se daría cuenta que está en presencia de un acontecimiento que lo cambia. Si estamos atentos a estos momentos, nos daríamos cuenta que tenemos la posibilidad de empezar de nuevo y con un nuevo maestro. Si estamos atentos a este acontecimiento no volvemos a ser los mismos que antes, nos cambia. Alguien decía que "el acontecimiento es como un martillazo en la cabeza, porque te cambia la vida". Este es uno de los momentos en los cuales se nos presenta la posibilidad de volver a ver cada paso con la simpleza de un niño. El ser humano es posibilidad, decía Heidegger, posibilidad, en este caso, de darle el peso necesario a ese "martillo" que es el acontecimiento para que nos cambie y ver el mundo de una forma mas simple, mas sencilla y mas amorosa.',
    home: false,
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/No_te_alejes_tanto_r5nrnj.png",
    title: "No te alejes tanto",
    detail: "Mixto sobre tela, 60 x 90 cm",
    think: 'La distancia. De corazón a corazón. Clara siente que cada vez se aleja mas ese corazón que la contenia y acompañaba, siente que va caminando cada vez mas sola. Hay una extrañeza que la embarga, que domina todos los momentos de su vida, que no puede ni siquiera contarle que le está pasando o que por error quemó una tostada, por ejemplo. La incomodidad es cada vez mayor y se da cuenta que ya no hay que seguir intentando acortar esa distancia entre ambas almas. Lo mejor es no oponerse a esa lejania y aceptar que el otro, con el tiempo será cada vez mas un extraño. Y no dejar que esto haga que pierda el deseo de compartir su vida con quien pueda tener una cercanía que la haga valorar cada minuto de su vida y cada respiración. Puede que haya puesto sus ojos en otro corazón? Si, puede ser, como que no puede ser. Lo importante es lo que Clara crea que es mejor para ella y para conservar ese deseo, intacto, de compartir su nexo con lo eterno. Oponerse a lo evidente es ser necio, y entrar en la necedad es abrir las puertas de miles de frustraciones que no la llevaran a nada mas que a un nihilismo. Clara sigue su camino, algo triste, algo abrumada, pero sabe que seguramente encontrará ese otro corazón que vibre en su misma frecuencia. El mio por ejemplo. La imagen me sugirió esa dureza de corazón, ese desinterés, ese distrato que se sabe dar en las relaciones. Que no es necesario, porque todo se habla y se dialoga.',
    home: false,
  },
  {
    id: 10,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Para_buscar_a_Clara_tsyvsa.jpg",
    title: "Para buscar a Clara",
    detail: "Mixto sobre tela, 70 x 50 cm.",
    think: 'Muchos quieren saber quien es Clara, bueno, yo también. Me han preguntado como es, me han enviado algunas canciones para que en mi concentración vea a Clara y la encuentre, otros me han hecho comentarios no muy alegres respecto de Clara, sin conocerla obviamente, prejuicios, solo eso. Aun no conozco a Clara, no sé quien es y no sé donde está. Si hay algunas cosas que conozco de ella, sus sueños, el lugar donde le gusta pasar algunas tardes, sé que le gustan las margaritas. Pero aun no he tenido un encuentro con ella o tal vez si, pero no me he dado cuenta. Me han preguntado quien es Clara para mi y porque la busco. Para mi Clara es un misterio y no sé muy bien porqué la busco, lo intuyo, pero creo que cuando la encuentre entenderé el porque de mi búsqueda y que significará para mi. En algún lugar está, existe. Se que en alguien habita. Creo que debo seguir y en algún momento, en algun ahora, en algun lugar, doblando una esquina tal vez.... encuentre a Clara. En la búsqueda también se aprende y se crece. En realidad todo esto, no es mas que un juego, de pensar que hay alguien, que tal vez ya conocemos, y con quien compartimos algunos momentos, no importa cuales, lleva en su interior este estereotipo de Clara, tal vez tapado por que solo vemos sus grises. Por tanto, también es una invitación a mirar en la otra persona sus blancos, sus virtudes y resaltarlas, y con delicadeza, amor y respeto abrazar sus grises, sus límites. Para que así éstos se fundan en las virtudes, porque unos fundamentan a los otros.',
    home: true,
  },
  {
    id: 11,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/De_amor_y_filosof%C3%ADa_ntjfnh.png",
    title: "De amor y filosofía",
    detail: "Mixto sobre tela, 100 x 100 cm.",
    think: 'Creo que el punto de unión, entre el amor y la filosofía, es justamente ese debate que se dá entre lo intelectual y lo carnal, ese límite finito en el que ambos coinciden en darle a la misma vida el sentido profundo de la experiencia, es el coincidir en la primicia del momento. Y asimismo, ese punto de unión, puede convertirse en el punto de divergencia entre dos personas, pero si la persona es la indicada esa divergencia se transforma en un puente hacia ese deseo de infinito y eternidad que te es dado solo por el amor. Porque pienso en la persona indicada? Porque, creo, que es la que te mantiene o acompaña a mantener viva esa primicia del ahora que se vive. La primicia, es el estupor del encuentro, con la realidad, con la persona. Eso que te viene como primera cosa que sentís y mantenerlo vivo es todo un arte. El mantenerse vivo, acompañar y ser acompañado en la primicia, es toda una atención al otro y así mismo. Es todo un arte, como el amor y la filosofía. De Amor y Filosofía se construyen los mejores momentos, los mejores ahoras, el mejor futuro, el más verdaderamente futuro amoroso.',
    home: false,
  },
  {
    id: 12,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/El_sue%C3%B1o_de_Clara_fdo9hx.jpg",
    title: "El sueño de Clara",
    detail: "Mixto sobre papel, 38 x 49 cm.",
    think: '¿Dónde va Clara cuando sueña? ¿A dónde viaja en su sueño? ¿Quién la acompaña en cada uno de sus viajes oníricos? ¿con quién sueña Clara? El sueño es una forma de materializar en los sentidos una realidad anhelada, amada, deseada, porque no temida. El sueño de Clara es tan vivido que no puede separar la realidad despierta de la soñada. ¿Dónde ella es más feliz? En su rostro se puede ver una sonrisa. Cuando entra en su sueño vive cerca de quien ama. Visita los lugares más raros y menos conocidos, pero siempre tienen esa familiaridad que le da su amada compañía. Nada es extraño mientras este su amor. Todo se transforma en familiar y amable. Alguien una vez me dijo "al lugar lo hacemos vos y yo. No importa donde esté, sino que esté con vos. Todo cambia si estamos juntos". Clara vive eso todas las noches. Ahí abunda la paz, la libertad y el amor. También, pero muy pocas veces, los miedos, que aparecen ante la ausencia de su compañía. Es el miedo a la ausencia, la soledad, el abandono, tal vez. Pero dura poco porque su amor siempre está presente. Clara en sus sueños es más feliz porque siempre es rescatada por la caricia y la mirada amorosa de su compañía. No hay campos verdes, ni cascadas, ni montañas, ni bosques, ni hogares encendidos, siestas al sol, que ella no haya vivido y disfrutado. Clara, todas las noches, después de trabajar, se da vueltas en la cama, mirando la pared, escucha la puerta cerrarse, cierra sus ojos, sonríe y vuelve a entrar en su mundo con su amor que la espera.',
    home: false,
  },
  {
    id: 13,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Clara_en_un_minuto_a8xxza.png",
    title: "Clara en un minuto",
    detail: "Mixto sobre papel.",
    think: 'Hay encuentros que son "mágicos", que cuando se producen te movilizan, te das cuenta que hay algo más, no sé cómo explicarlo, pero es como encontrarte con alguien que te pone frente al infinito. No quiero decir que te completa, porque es un bardo, algunos dicen que estamos completos y otros que tenemos y sufrimos una falta, yo la verdad que no sé si te completa o no, pero sí sé que te mueve algo adentro tuyo y sabes que esa persona te transporta a un estado de estupor y deseo. Y ese encuentro es como definitorio, sabes que ya está, no sabes cómo, pero sabes que ya está y que esa persona es la que de alguna manera corresponde a tu corazón, o tu yo, o a lo que sos. Cuando dibujé a Clara, así, en un minuto, supe mágicamente que ella era quien debía estar ahí y el resto no importaba. Lo que estuviera alrededor, las palabras que se dijeran o escribieran, por más profundas y sentidas que fueran, no importaban. Todo se diluía y desvanecía con solo su presencia. Si, ya sé, es un dibujo, en un papel, con lápiz y tinta china, con un montón de colores y trazos. No es el objeto lo importante, es lo que significa como encuentro, lo mágico que te pone frente a la belleza de la vida, que es encontrar a quien te corresponde, y no importa si es en una obra o en una persona, es que ese encuentro te dice "aquí es donde querés estar". Te pone frente a tu deseo de infinito. Ojalá todos podamos experimentar esto.',
    home: false,
  },
  {
    id: 14,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Quiz%C3%A1_nos_vaya_mejor_ca80c9.png",
    title: "Quizá nos vaya mejor",
    detail: "Mixto sobre tela, 60 cm x 80 cm.",
    think: 'Tengo muchas cosas en la cabeza para escribir cuando veo esta obra. Muchos recuerdos, pensamientos y reflexiones me vienen al encuentro, pero creo que lo que más me gustaría resaltar es ese momento en que te das cuenta que tus hijos crecieron. Y las conversaciones con ellos son cada vez más maduras, más profundas y con un sentido de la vida que te da orgullo que tus hijos piensen y hablen así. Y aún persiste, en mí, en vos, esa imagen y ese sentimiento, que tus hijos eran o son aún, en su interior, ese niño o niña, hermoso, que viste crecer y convertirse en un ser maravilloso. Esta obra está fundamentada en esas palabras que los hijos, tus hijos, mis hijos, palabras que son frutos de su crecimiento, nos regalan para que nosotros también sigamos madurando y aprendiendo. Algunos, como Augus, ponen esas palabras en las letras de sus canciones, donde dejan sus deseos, anhelos, frustraciones, enojos, amores, amistades, esperanzas, pedidos... como no escucharlas, como no atesorarlas en el corazón, si están poniendo en ellas toda su vida y lo que ellos viven como pueden. Agradezco, a la vida este regalo que me da.',
    home: false,
  },
  {
    id: 15,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418784/Galeria%20R.P%20imagenes%20optimizadas/Clara_y_sus_margaritas_gmyxuz.png",
    title: "Clara y sus margaritas",
    detail: "Mixto sobre tela, 80 x 100 cm.",
    think: 'Clara, algunas tardes de otoño, las primeras tardes, esas cuando aún el sol sigue la inercia del verano, sale a caminar por el campo, siguiendo el sendero que la lleva a esa pequeña laguna, donde ella, muy libremente toma un baño. Deja sus ropas sobre el tronco de un sauce caído y entra al agua, aun cálida.Disfrutando del agua, y el sonido que hace cuando ella se mueve, y el canto de los pájaros, y el sonido de alguna pequeña brisa sobre las ramas de los árboles, mira el lugar donde a ella le gusta tomar sol y secarse. Un pequeño claro, donde crecen margaritas silvestres, donde el pasto es más suave, donde el sol entra más franco. Le gusta porque además de poder estar entre sus flores favoritas y en la comodidad del suelo, le recuerda a los paseos que daba con su abuela materna. La transporta a esos momentos y recuerda, con mucho amor, la calidez con que su abuela contaba las historias de las margaritas, de cómo esas jóvenes mujeres se convirtieron en flores, para poder vestir al campo de belleza y sencillez. Mira las flores, imagina a esas sencillas doncellas que se volvieron belleza natural y entiende que su abuela también es una de ellas, por eso mira y siente... Clara quiere ser margarita...',
    home: false,
  },
  {
    id: 16,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/La_codicia_humana_q1qodb.jpg",
    title: "La codicia humana",
    detail: "Mixto sobre papel, 45 x 30 cm.",
    think: 'Buscando una nueva estética, donde poder expresar aún más esta cosa que tengo dentro que es muy difícil de sacar. No es bronca, no es enojo, es como una frustración de ver cómo estamos socavando nuestra sociedad, nuestra cultura, nuestra civilización. A veces no puedo entender por qué se hacen las cosas sin importar mucho lo que pueda suceder al resto de las personas. Tiendo a explicar esos actos como fruto de un cinismo alienante pero no logro entender como no hay un fondo que haga que eso pare. Cuando lo escucho a DZ que dice "en el fondo no hay fondo" pienso que es eso. Pero no me conforma. El ser humano vive preso de su codicia, hija de creer que hay una infinitud en la vida, una eternidad. ¡Vivimos pensando que nos vamos a salvar!!! Unos creen en un edén, un paraíso, otros, los adinerados, en una terraformacion de marte, otros, los cinéfilos pochocleros, que se pueden refugiar en un bunker hecho por los americanos. La realidad es que no hay salvación individual, te morís chabón!! ¡Solo hay salvación de la especie!!!',
    home: false,
  },
  {
    id: 17,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Acerca_de_los_or%C3%ADgenes_zpt8nh.png",
    title: "Acerca de los orígenes",
    detail: "Mixto sobre tela, 90 x 70 cm.",
    think: 'Me gusta creer que mis orígenes tienen que ver con los pueblos más antiguos de la historia, me gusta jugar y fantasear con esa posibilidad. En las proximidades de la historia mis orígenes en realidad son de tierras no muy lejanas, pero siempre me pregunto de donde vinieron mis ancestros más allá de mis tatarabuelos. La fantasía me hace pensar que los orígenes son celtas, árabes, nórdicos. Eso me ha llevado a escuchar música de esos pueblos, leer su mitología, su historia, su expansión. Y todo en mi cabeza pasa como una película épica. Hace unas semanas tuve la posibilidad de estar en una feria medieval, eso alimentó aún más mi imaginación y cuando me leyeron las runas, fue un flash hacia la mitología nórdica. Odin, Thor, Freya, Freyr... volé. Y fue una buena oportunidad para poder leer y buscar y después jugar y plasmar algunas palabras o frases en rúnico en alguno de mis trabajos.',
    home: true,
  },
  {
    id: 18,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418784/Galeria%20R.P%20imagenes%20optimizadas/Aun_as%C3%AD_renace_kubwpv.png",
    title: "Aun asi renace",
    detail: "Mixto sobre tela, 90 x 70 cm.",
    think: 'Más allá de las imposiciones culturales, sociales, económicas, el yo siempre emerge, de una forma u otra, no soporta el hecho de estar atado, amarrado, tapado, siempre sale a flote, siempre genera un caos, interno o externo, pero sale y en un momento comienza a florecer. El reordenamiento del yo rompe con todo orden establecido y no importan las consecuencias, importa ese renacer. Lo mismo pasa en las sociedades en un momento despiertan las personas y dejan de comer lo que le dan, empiezan a elegir lo que quieren comer. Eso también genera caos, revuelta, rebelión y una revolución.',
    home: false,
  },
  {
    id: 19,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Saliendo_de_la_anestesia_iq81by.png",
    title: "Saliendo de la anestesia",
    detail: "Acrílico sobre tela, 100 x 70 cm.",
    think: 'Cuando uno va saliendo de la anestesia, se siente como que sale de una niebla medio rara. De la misma forma, el yo verdadero, experimenta esa salida de las sombras de la niebla cuando va dejando atrás todos los mandatos y programaciones sufridas, que vienen dadas por la sociedad. Cuando uno se da cuenta que no sos lo que otros te han dicho que sos y debes hacer, empezas a salir de la anestesia para ser vos mismo. Encontrás en vos un caos. Bienvenido el caos.',
    home: false,
  },
  {
    id: 20,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Sirena_o_Mariposa_qip1zn.png",
    title: "Sirena o mariposa",
    detail: "Mixto sobre tela, 70 x 50 cm.",
    think: 'Sirena o mariposa, su rostro no se ve, no hay forma de mostrarla. Se esconde, detrás de inseguridades e indecisiones. Pero su naturaleza no se pierde, cada vez es más concreta, de a poco se va alejando de esa nebulosa de cuentos y de fantasía que desdibujan su rostro. La han visto en el mar, nadando cerca de la costa, tomando sol en la arena de la playa, caminando y juntando caracoles. La han visto remontando vuelo, extendiendo sus alas para que el viento marino la eleve. Y en su vuelo pasa cerca, muy cerca, casi como para poder tocarla. Pero no se deja, es esquiva, se protege. Abre sus alas, pero aún no su corazón. Yo sé que está cerca el día del encuentro. Y la risa será eterna.',
    home: false,
  },
  {
    id: 21,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/Keep_breathing_mdahc5.png",
    title: "Keep breathing",
    detail: "Mixto sobre papel",
    think: 'Este es del 2020, hay mucho corona, mucha ansiedad dando vueltas, dudas, stress, administrar ansiedades ajenas, todo producido obviamente por el hecho pandémico que todos sufrimos. Muchas cosas pasaron en el 2020, muchos momentos en los que me faltó el aire, me ahogaba, necesitaba respirar y mi fuente de oxígeno estaba lejos e imposible de llegar. De veras que pasé momentos en los que no sabía cómo seguir y solo tenía en mi mente un camino a través de árboles, montañas, silencio y soledad. Había que mantener el aliento, seguir respirando, hasta que pudiera oxigenar mejor. Esta obrita es parte y alguna de todo ese proceso. Hace unas semanas atrás una señora viendo una obra de esta serie me preguntó si estaba enojado en ese momento, le respondí que más que nada estaba angustiado. La señora, ya mayor, era psicóloga.',
    home: false,
  },
]