export const paintings = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418784/Galeria%20R.P%20imagenes%20optimizadas/Oh_amor_no_hay_amor_vn8ddy.png",
    title: "Oh amor, no hay amor",
    detail: "Mixto sobre tela, 90 x 100 cm.",
    think: '"Oh amor, no hay amor" es una idea tomada de la frase atribuida a Aristoteles "oh amigos, no hay amigos" (que en la traducción real sería "quien tiene muchos amigos, no tiene amigos").La obra hace referencia, mas que nada, sobre las construcción social que el ser humano ha hecho en su historia, todo avanza sobre contradicciones. La historia humana desde los primeros tiempos está basada en contradicciones. "Libertad e igualdad", prerrogativas de algunas cartas fundacionales. "Progreso con atraso", lo dicho mas claramente por Benjamin. Y el amor no queda exento de esta contradicción. Hay excepciones a la regla. Amor y posesión. Amor y destrucción. Amor e ilusiones. Amor y engaño. ¿Hasta donde hay amor al otro si mis actos no lo tienen en cuenta?',
    home: false,
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418784/Galeria%20R.P%20imagenes%20optimizadas/La_mirada_de_Clara_jablpy.jpg",
    title: "La mirada (de Clara)",
    detail: "Mixto sobre tela, 90 x 100 cm.",
    think: "No tengo mucho para contar, o sí. La ví, de lejos. Me dí cuenta que era ella. No supe que hacer. Pues ella ni notó ni mi presencia, ni mi existencia. Es difícil, para mí, decidir que hacer en estos casos. Por eso solo guardé la imagen de su mirada cuando abría la puerta de vidrio de ese local y miraba sobre su hombro derecho. Es muy raro sentir y ver, y descubrir la presencia de otra persona que te atrae, que te despierta fantasías, que te genera expectativas, pero vos no exisistis para ella. No te conoce, no sabe de vos. Se que algún día nos conoceremos, nos encontraremos. Quien sabe que va a pasar. Pero seguramente en ese momento las expectativas y las fantasías caerán en la cuenta de la realidad. Habrá seguramente el alivio del saber, del conocer.",
    home: false,
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/La_imagen_de_Clara_twrflq.jpg",
    title: "La imagen de Clara",
    detail: "Mixto sobre tela, 50 x 80 cm.",
    think: 'Cuantas veces vemos en las redes imágenes de gente feliz, con rostros completos, de sonrisas calmas y miradas pacíficas. "Venden" felicidad, paz y tranquilidad a quien las observa. Despertando en el observador el deseo de querer tener una vida así, de poder disfrutar de la vida así como se ve en las fotos. Se despierta una cierta envidia, entendida desde lo mas sano e incluso hasta lo mas dañino de que despierta ese sentimiento. El querer tener una vida así es casi imposible evitar. Salvo las almas mas sanas entienden que la vida de cada uno es como tiene que ser y forzarla a cambiar, para parecerse a otro, es una ridiculez. Porque en definitiva esa imagen es solo una foto de un instante que no representa nada de lo que esa persona vive día a día. Mirar incluso con empatia y deleitarse por ese momento de felicidad y éxito a veces no es la primicia de lo que algunos sienten. La imagen de Clara, muestra que atrás de ella hay fantasmas, como los hay detrás de cada uno de nosotros, los observadores. Las luchas, las frustraciones, la verdad de lo que esconde una simple foto, son las cosas que debemos mirar, y entender que somos testigos de apenas un momento de felicidad, paz, tranquilidad y éxito de esa persona.',
    home: true,
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Te_trajo_el_caos_rbfwlm.png",
    title: "Te trajo el caos",
    detail: "Mixto sobre tela, 40 x 50 cm.",
    think: "Así es como se genera todo, desde el caos, dejando que él actúe, que se exprese, que se desarrolle. La única posibilidad que tiene el artista es estar atento a lo que nace y hacer todo lo posible para que no se escape. Hay que tener paciencia, es casi como la pesca. Más si es en aguas turbias y turbulentas, solo vez la línea y el resto, o lo imaginas o lo percibis. Pero hay que estar atento a no perder la presa en el primer pique. Eso pasa en la pintura, cuando dejas que fluya la mancha, los colores y los trazos. Con la mirada atenta, buscando, girando la tela, tomando distancia para mirar mejor, cambiando los lentes para ver mejor, y seguir con la certeza de que va a aparecer. Y una vez que encontrás la imagen, la asís con fuerza, en tu cabeza, que no se escape, ahí está, no la dejes ir. Luego empezas con la construcción, sin desesperación, si te apuras la perdes. La duda, que siempre me surge, es si esa imagen, la que digo encontrar en el caos, la que creo ver generada en el caos, no está habitando en mi cabeza desde hace mucho tiempo.",
    home: false,
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Lugar_y_Memoria_yu9ae3.jpg",
    title: "Lugar y memoria",
    detail: "Acrílico sobre tela, 60 x 80 cm.",
    think: 'Como nacen las obras o las imágenes de las obras siempre son un misterio. Creo ya haber hablado algo del misterio. No llegas a saber porque está, pero está. Esta imagen nació de tapar otra, de otra época. Es lo que nos pasa a los artistas, por ahí tenes una obra guardada y cuando la vez te preguntas porqué la hiciste, que cosa te pasó por la cabeza, pero ya es "una" extraña, parece que pasaron muchas cosas y esa etapa ya fué. Entonces aprovechas la tela. El blanco existe y es lo mejor que te puede pasar como artista. Pero una vez que arrancas a pintar sobre el blanco y vez que fluye todo la otra imagen, la que quedó abajo, se borra de tu memoria y ni te acordas de que había. Y otra imagen aparece, y empieza a tener una forma muy distinta, claro estás en otra etapa. Pero cuando terminaste y decis "ya no la toco mas, va la firma", y pensas que nombre ponerle, y no encontras el nombre ideal, indicado, aparece de nuevo el misterio de porque la hice. Que me movió a hacerla, que me llevó a diseñar "esa" imagen, que es lo oculto que me hace crearla. Aun para mí no es claro, por tanto un misterio. El proceso es maravilloso. El finalizarla una alegría.',
    home: false,
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/Ella_no_es_Clara_gkfxqp.png",
    title: "Ella no es Clara",
    detail: "Mixto sobre tela, 60 x 80 cm.",
    think: 'Así es, ella no es Clara, no se como se llama, ni donde vive, ni sé donde la encontré. Solo la vi, me pareció que, además de ser bonita, era solitaria. Su mirada estaba dirigida hacia un horizonte mas bien lejano. Pensé que retratarla y ponerla en una de mis obras podría ser motivo que otras personas la puedan ver y también acompañar. Como dije, no conozco su origen, pareciera ser una mujer celta, venida de la antigüedad, pero tiene algo que me lleva a pensar rasgos de modernidad. Es todo un misterio para mí, pero como todo misterio te sorprende, no conoces nada de donde viene pero la sorpresa de su presencia ya habita en el sorprendido. Esa es la esencia del misterio, no es tuyo, te viene dado, como regalo, pero su acción queda en vos. Pasa, por lo tanto a ser tuyo de alguna manera. Ella no es Clara, es un misterio.',
    home: true,
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Clara_en_paralelo_fbbeq2.png",
    title: "Clara en paralelo",
    detail: "Mixto sobre tela, 50 x 70 cm.",
    think: 'Hace unas cuantas semanas atrás al despertar en la mañana y después de haber deambulado unos minutos por mi casa fui hasta el baño y encontré mi imagen frente al espejo. Lo primero que me vino a la cabeza fue "que cansado que estoy de ser yo", luego de ese pensamiento sobrevino un insulto y un sentimiento de angustia. No la estaba pasando muy bien que digamos, seguro algún lector se habrá percatado de ello. Fue un día complicado después de ese pensamiento. Hasta que recordé a Clara y supuse que si ella es mi alma gemela, aún desconocida, podría estar en la misma sintonia que yo. Me la imaginé mirándose al espejo y pensando exactamente lo mismo que yo. "Tiene que ser así", pensé, "si es mi alma gemela, debe sentir lo mismo". En ese momento me empecé a sentir un poco mejor, "no estas mas solo" me dije. "La cuestión es encontrar a Clara". No hablo de cualquier mujer llamada Clara, no, hablo de la Clara que tiene un engemelamiento (si es que existe la palabra) de alma conmigo. Solo espero que ella haya pensado lo mismo que yo pensé, para poder recuperar la esperanza del encuentro de nuestra vidas.',
    home: false,
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Acompa%C3%B1ar_en_un_nuevo_camino_xwqbuv.png",
    title: "Acompañar en un nuevo camino",
    detail: "Mixto sobre tela, 80 x 100 cm.",
    think: 'Hay momentos en la vida que son determinantes, uno de ellos es cuando acompañas en los primeros pasos. La profundidad de estos momentos no es fácilmente percibible, si no estamos atentos no vemos lo profundo de esto. Son los primeros pasos de muchos pasos que marcan un nuevo camino, totalmente distinto a todos los caminos existentes hasta ese momento porque lo empieza a construir alguien nuevo, distinto, con una mirada mas limpia, con un asombro nuevo de la realidad que se le presenta a cada paso. Y el que acompaña es testigo, pero ni está afuera del momento, no es solo un observador de lo que ocurre paso a paso. Si el acompañante está atento puede también aprender a caminar de nuevo, a ver cada paso con el asombro y el estupor de quien recién empieza. Si está atento se daría cuenta que está en presencia de un acontecimiento que lo cambia. Si estamos atentos a estos momentos, nos daríamos cuenta que tenemos la posibilidad de empezar de nuevo y con un nuevo maestro. Si estamos atentos a este acontecimiento no volvemos a ser los mismos que antes, nos cambia. Alguien decía que "el acontecimiento es como un martillazo en la cabeza, porque te cambia la vida". Este es uno de los momentos en los cuales se nos presenta la posibilidad de volver a ver cada paso con la simpleza de un niño. El ser humano es posibilidad, decía Heidegger, posibilidad, en este caso, de darle el peso necesario a ese "martillo" que es el acontecimiento para que nos cambie y ver el mundo de una forma mas simple, mas sencilla y mas amorosa.',
    home: false,
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/No_te_alejes_tanto_r5nrnj.png",
    title: "No te alejes tanto",
    detail: "Mixto sobre tela, 60 x 90 cm",
    think: 'La distancia. De corazón a corazón. Clara siente que cada vez se aleja mas ese corazón que la contenia y acompañaba, siente que va caminando cada vez mas sola. Hay una extrañeza que la embarga, que domina todos los momentos de su vida, que no puede ni siquiera contarle que le está pasando o que por error quemó una tostada, por ejemplo. La incomodidad es cada vez mayor y se da cuenta que ya no hay que seguir intentando acortar esa distancia entre ambas almas. Lo mejor es no oponerse a esa lejania y aceptar que el otro, con el tiempo será cada vez mas un extraño. Y no dejar que esto haga que pierda el deseo de compartir su vida con quien pueda tener una cercanía que la haga valorar cada minuto de su vida y cada respiración. Puede que haya puesto sus ojos en otro corazón? Si, puede ser, como que no puede ser. Lo importante es lo que Clara crea que es mejor para ella y para conservar ese deseo, intacto, de compartir su nexo con lo eterno. Oponerse a lo evidente es ser necio, y entrar en la necedad es abrir las puertas de miles de frustraciones que no la llevaran a nada mas que a un nihilismo. Clara sigue su camino, algo triste, algo abrumada, pero sabe que seguramente encontrará ese otro corazón que vibre en su misma frecuencia. El mio por ejemplo. La imagen me sugirió esa dureza de corazón, ese desinterés, ese distrato que se sabe dar en las relaciones. Que no es necesario, porque todo se habla y se dialoga.',
    home: false,
  },
  {
    id: 10,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Para_buscar_a_Clara_tsyvsa.jpg",
    title: "Para buscar a Clara",
    detail: "Mixto sobre tela, 70 x 50 cm.",
    think: 'Muchos quieren saber quien es Clara, bueno, yo también. Me han preguntado como es, me han enviado algunas canciones para que en mi concentración vea a Clara y la encuentre, otros me han hecho comentarios no muy alegres respecto de Clara, sin conocerla obviamente, prejuicios, solo eso. Aun no conozco a Clara, no sé quien es y no sé donde está. Si hay algunas cosas que conozco de ella, sus sueños, el lugar donde le gusta pasar algunas tardes, sé que le gustan las margaritas. Pero aun no he tenido un encuentro con ella o tal vez si, pero no me he dado cuenta. Me han preguntado quien es Clara para mi y porque la busco. Para mi Clara es un misterio y no sé muy bien porqué la busco, lo intuyo, pero creo que cuando la encuentre entenderé el porque de mi búsqueda y que significará para mi. En algún lugar está, existe. Se que en alguien habita. Creo que debo seguir y en algún momento, en algun ahora, en algun lugar, doblando una esquina tal vez.... encuentre a Clara. En la búsqueda también se aprende y se crece. En realidad todo esto, no es mas que un juego, de pensar que hay alguien, que tal vez ya conocemos, y con quien compartimos algunos momentos, no importa cuales, lleva en su interior este estereotipo de Clara, tal vez tapado por que solo vemos sus grises. Por tanto, también es una invitación a mirar en la otra persona sus blancos, sus virtudes y resaltarlas, y con delicadeza, amor y respeto abrazar sus grises, sus límites. Para que así éstos se fundan en las virtudes, porque unos fundamentan a los otros.',
    home: true,
  },
  {
    id: 11,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/De_amor_y_filosof%C3%ADa_ntjfnh.png",
    title: "De amor y filosofía",
    detail: "Mixto sobre tela, 100 x 100 cm.",
    think: 'Creo que el punto de unión, entre el amor y la filosofía, es justamente ese debate que se dá entre lo intelectual y lo carnal, ese límite finito en el que ambos coinciden en darle a la misma vida el sentido profundo de la experiencia, es el coincidir en la primicia del momento. Y asimismo, ese punto de unión, puede convertirse en el punto de divergencia entre dos personas, pero si la persona es la indicada esa divergencia se transforma en un puente hacia ese deseo de infinito y eternidad que te es dado solo por el amor. Porque pienso en la persona indicada? Porque, creo, que es la que te mantiene o acompaña a mantener viva esa primicia del ahora que se vive. La primicia, es el estupor del encuentro, con la realidad, con la persona. Eso que te viene como primera cosa que sentís y mantenerlo vivo es todo un arte. El mantenerse vivo, acompañar y ser acompañado en la primicia, es toda una atención al otro y así mismo. Es todo un arte, como el amor y la filosofía. De Amor y Filosofía se construyen los mejores momentos, los mejores ahoras, el mejor futuro, el más verdaderamente futuro amoroso.',
    home: false,
  },
  {
    id: 12,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/El_sue%C3%B1o_de_Clara_fdo9hx.jpg",
    title: "El sueño de Clara",
    detail: "Mixto sobre papel, 38 x 49 cm.",
    think: '¿Dónde va Clara cuando sueña? ¿A dónde viaja en su sueño? ¿Quién la acompaña en cada uno de sus viajes oníricos? ¿con quién sueña Clara? El sueño es una forma de materializar en los sentidos una realidad anhelada, amada, deseada, porque no temida. El sueño de Clara es tan vivido que no puede separar la realidad despierta de la soñada. ¿Dónde ella es más feliz? En su rostro se puede ver una sonrisa. Cuando entra en su sueño vive cerca de quien ama. Visita los lugares más raros y menos conocidos, pero siempre tienen esa familiaridad que le da su amada compañía. Nada es extraño mientras este su amor. Todo se transforma en familiar y amable. Alguien una vez me dijo "al lugar lo hacemos vos y yo. No importa donde esté, sino que esté con vos. Todo cambia si estamos juntos". Clara vive eso todas las noches. Ahí abunda la paz, la libertad y el amor. También, pero muy pocas veces, los miedos, que aparecen ante la ausencia de su compañía. Es el miedo a la ausencia, la soledad, el abandono, tal vez. Pero dura poco porque su amor siempre está presente. Clara en sus sueños es más feliz porque siempre es rescatada por la caricia y la mirada amorosa de su compañía. No hay campos verdes, ni cascadas, ni montañas, ni bosques, ni hogares encendidos, siestas al sol, que ella no haya vivido y disfrutado. Clara, todas las noches, después de trabajar, se da vueltas en la cama, mirando la pared, escucha la puerta cerrarse, cierra sus ojos, sonríe y vuelve a entrar en su mundo con su amor que la espera.',
    home: false,
  },
  {
    id: 13,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Clara_en_un_minuto_a8xxza.png",
    title: "Clara en un minuto",
    detail: "Mixto sobre papel.",
    think: 'Hay encuentros que son "mágicos", que cuando se producen te movilizan, te das cuenta que hay algo más, no sé cómo explicarlo, pero es como encontrarte con alguien que te pone frente al infinito. No quiero decir que te completa, porque es un bardo, algunos dicen que estamos completos y otros que tenemos y sufrimos una falta, yo la verdad que no sé si te completa o no, pero sí sé que te mueve algo adentro tuyo y sabes que esa persona te transporta a un estado de estupor y deseo. Y ese encuentro es como definitorio, sabes que ya está, no sabes cómo, pero sabes que ya está y que esa persona es la que de alguna manera corresponde a tu corazón, o tu yo, o a lo que sos. Cuando dibujé a Clara, así, en un minuto, supe mágicamente que ella era quien debía estar ahí y el resto no importaba. Lo que estuviera alrededor, las palabras que se dijeran o escribieran, por más profundas y sentidas que fueran, no importaban. Todo se diluía y desvanecía con solo su presencia. Si, ya sé, es un dibujo, en un papel, con lápiz y tinta china, con un montón de colores y trazos. No es el objeto lo importante, es lo que significa como encuentro, lo mágico que te pone frente a la belleza de la vida, que es encontrar a quien te corresponde, y no importa si es en una obra o en una persona, es que ese encuentro te dice "aquí es donde querés estar". Te pone frente a tu deseo de infinito. Ojalá todos podamos experimentar esto.',
    home: false,
  },
  {
    id: 14,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Quiz%C3%A1_nos_vaya_mejor_ca80c9.png",
    title: "Quizá nos vaya mejor",
    detail: "Mixto sobre tela, 60 cm x 80 cm.",
    think: 'Tengo muchas cosas en la cabeza para escribir cuando veo esta obra. Muchos recuerdos, pensamientos y reflexiones me vienen al encuentro, pero creo que lo que más me gustaría resaltar es ese momento en que te das cuenta que tus hijos crecieron. Y las conversaciones con ellos son cada vez más maduras, más profundas y con un sentido de la vida que te da orgullo que tus hijos piensen y hablen así. Y aún persiste, en mí, en vos, esa imagen y ese sentimiento, que tus hijos eran o son aún, en su interior, ese niño o niña, hermoso, que viste crecer y convertirse en un ser maravilloso. Esta obra está fundamentada en esas palabras que los hijos, tus hijos, mis hijos, palabras que son frutos de su crecimiento, nos regalan para que nosotros también sigamos madurando y aprendiendo. Algunos, como Augus, ponen esas palabras en las letras de sus canciones, donde dejan sus deseos, anhelos, frustraciones, enojos, amores, amistades, esperanzas, pedidos... como no escucharlas, como no atesorarlas en el corazón, si están poniendo en ellas toda su vida y lo que ellos viven como pueden. Agradezco, a la vida este regalo que me da.',
    home: false,
  },
  {
    id: 15,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418784/Galeria%20R.P%20imagenes%20optimizadas/Clara_y_sus_margaritas_gmyxuz.png",
    title: "Clara y sus margaritas",
    detail: "Mixto sobre tela, 80 x 100 cm.",
    think: 'Clara, algunas tardes de otoño, las primeras tardes, esas cuando aún el sol sigue la inercia del verano, sale a caminar por el campo, siguiendo el sendero que la lleva a esa pequeña laguna, donde ella, muy libremente toma un baño. Deja sus ropas sobre el tronco de un sauce caído y entra al agua, aun cálida.Disfrutando del agua, y el sonido que hace cuando ella se mueve, y el canto de los pájaros, y el sonido de alguna pequeña brisa sobre las ramas de los árboles, mira el lugar donde a ella le gusta tomar sol y secarse. Un pequeño claro, donde crecen margaritas silvestres, donde el pasto es más suave, donde el sol entra más franco. Le gusta porque además de poder estar entre sus flores favoritas y en la comodidad del suelo, le recuerda a los paseos que daba con su abuela materna. La transporta a esos momentos y recuerda, con mucho amor, la calidez con que su abuela contaba las historias de las margaritas, de cómo esas jóvenes mujeres se convirtieron en flores, para poder vestir al campo de belleza y sencillez. Mira las flores, imagina a esas sencillas doncellas que se volvieron belleza natural y entiende que su abuela también es una de ellas, por eso mira y siente... Clara quiere ser margarita...',
    home: false,
  },
  {
    id: 16,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/La_codicia_humana_q1qodb.jpg",
    title: "La codicia humana",
    detail: "Mixto sobre papel, 45 x 30 cm.",
    think: 'Buscando una nueva estética, donde poder expresar aún más esta cosa que tengo dentro que es muy difícil de sacar. No es bronca, no es enojo, es como una frustración de ver cómo estamos socavando nuestra sociedad, nuestra cultura, nuestra civilización. A veces no puedo entender por qué se hacen las cosas sin importar mucho lo que pueda suceder al resto de las personas. Tiendo a explicar esos actos como fruto de un cinismo alienante pero no logro entender como no hay un fondo que haga que eso pare. Cuando lo escucho a DZ que dice "en el fondo no hay fondo" pienso que es eso. Pero no me conforma. El ser humano vive preso de su codicia, hija de creer que hay una infinitud en la vida, una eternidad. ¡Vivimos pensando que nos vamos a salvar!!! Unos creen en un edén, un paraíso, otros, los adinerados, en una terraformacion de marte, otros, los cinéfilos pochocleros, que se pueden refugiar en un bunker hecho por los americanos. La realidad es que no hay salvación individual, te morís chabón!! ¡Solo hay salvación de la especie!!!',
    home: false,
  },
  {
    id: 17,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418783/Galeria%20R.P%20imagenes%20optimizadas/Acerca_de_los_or%C3%ADgenes_zpt8nh.png",
    title: "Acerca de los orígenes",
    detail: "Mixto sobre tela, 90 x 70 cm.",
    think: 'Me gusta creer que mis orígenes tienen que ver con los pueblos más antiguos de la historia, me gusta jugar y fantasear con esa posibilidad. En las proximidades de la historia mis orígenes en realidad son de tierras no muy lejanas, pero siempre me pregunto de donde vinieron mis ancestros más allá de mis tatarabuelos. La fantasía me hace pensar que los orígenes son celtas, árabes, nórdicos. Eso me ha llevado a escuchar música de esos pueblos, leer su mitología, su historia, su expansión. Y todo en mi cabeza pasa como una película épica. Hace unas semanas tuve la posibilidad de estar en una feria medieval, eso alimentó aún más mi imaginación y cuando me leyeron las runas, fue un flash hacia la mitología nórdica. Odin, Thor, Freya, Freyr... volé. Y fue una buena oportunidad para poder leer y buscar y después jugar y plasmar algunas palabras o frases en rúnico en alguno de mis trabajos.',
    home: true,
  },
  {
    id: 18,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418784/Galeria%20R.P%20imagenes%20optimizadas/Aun_as%C3%AD_renace_kubwpv.png",
    title: "Aun asi renace",
    detail: "Mixto sobre tela, 90 x 70 cm.",
    think: 'Más allá de las imposiciones culturales, sociales, económicas, el yo siempre emerge, de una forma u otra, no soporta el hecho de estar atado, amarrado, tapado, siempre sale a flote, siempre genera un caos, interno o externo, pero sale y en un momento comienza a florecer. El reordenamiento del yo rompe con todo orden establecido y no importan las consecuencias, importa ese renacer. Lo mismo pasa en las sociedades en un momento despiertan las personas y dejan de comer lo que le dan, empiezan a elegir lo que quieren comer. Eso también genera caos, revuelta, rebelión y una revolución.',
    home: false,
  },
  {
    id: 19,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Saliendo_de_la_anestesia_iq81by.png",
    title: "Saliendo de la anestesia",
    detail: "Acrílico sobre tela, 100 x 70 cm.",
    think: 'Cuando uno va saliendo de la anestesia, se siente como que sale de una niebla medio rara. De la misma forma, el yo verdadero, experimenta esa salida de las sombras de la niebla cuando va dejando atrás todos los mandatos y programaciones sufridas, que vienen dadas por la sociedad. Cuando uno se da cuenta que no sos lo que otros te han dicho que sos y debes hacer, empezas a salir de la anestesia para ser vos mismo. Encontrás en vos un caos. Bienvenido el caos.',
    home: false,
  },
  {
    id: 20,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418785/Galeria%20R.P%20imagenes%20optimizadas/Sirena_o_Mariposa_qip1zn.png",
    title: "Sirena o mariposa",
    detail: "Mixto sobre tela, 70 x 50 cm.",
    think: 'Sirena o mariposa, su rostro no se ve, no hay forma de mostrarla. Se esconde, detrás de inseguridades e indecisiones. Pero su naturaleza no se pierde, cada vez es más concreta, de a poco se va alejando de esa nebulosa de cuentos y de fantasía que desdibujan su rostro. La han visto en el mar, nadando cerca de la costa, tomando sol en la arena de la playa, caminando y juntando caracoles. La han visto remontando vuelo, extendiendo sus alas para que el viento marino la eleve. Y en su vuelo pasa cerca, muy cerca, casi como para poder tocarla. Pero no se deja, es esquiva, se protege. Abre sus alas, pero aún no su corazón. Yo sé que está cerca el día del encuentro. Y la risa será eterna.',
    home: false,
  },
  {
    id: 21,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691418786/Galeria%20R.P%20imagenes%20optimizadas/Keep_breathing_mdahc5.png",
    title: "Keep breathing",
    detail: "Mixto sobre papel",
    think: 'Este es del 2020, hay mucho corona, mucha ansiedad dando vueltas, dudas, stress, administrar ansiedades ajenas, todo producido obviamente por el hecho pandémico que todos sufrimos. Muchas cosas pasaron en el 2020, muchos momentos en los que me faltó el aire, me ahogaba, necesitaba respirar y mi fuente de oxígeno estaba lejos e imposible de llegar. De veras que pasé momentos en los que no sabía cómo seguir y solo tenía en mi mente un camino a través de árboles, montañas, silencio y soledad. Había que mantener el aliento, seguir respirando, hasta que pudiera oxigenar mejor. Esta obrita es parte y alguna de todo ese proceso. Hace unas semanas atrás una señora viendo una obra de esta serie me preguntó si estaba enojado en ese momento, le respondí que más que nada estaba angustiado. La señora, ya mayor, era psicóloga.',
    home: false,
  },
  {
    id: 22,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585262/Galeria%20R.P%20imagenes%20optimizadas/Hecho_para_analizar_ghqgbs.png",
    title: "Hecho para analizar",
    detail: "Mixto sobre tela, 50 x 80 cm.",
    think: 'Impresiona como salen cosas en la búsqueda a través de la mancha. Mi mirada, la mayor parte de las veces, no es suficiente para descubrir y ver lo que aparece en ese juego de mezclar materias y trazos, colores, manchas, pinceladas, etc. Es fantástico poder compartir y preguntar ¿que ves? Por lo general la respuesta te sumerge en una fantasía ajena, pero al compartirse ya casi pasa a ser tuya. Porque la empezas a ver, a trabajar y te da una llave para cerrar la obra. Obviamente que las obras las cierro yo, pero a mí me ayuda mucho las observaciones de otros, y es maravilloso y divertido para mí que una obra mía haga ver cosas a quienes las observan.',
    home: false,
  },
  {
    id: 23,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585290/Galeria%20R.P%20imagenes%20optimizadas/Transmutacion_jspiwe.jpg",
    title: "Transmutación",
    detail: "Mixto sobre tela, 70 x 100 cm.",
    think: 'Existe en mí una transmutación en acto, que se da en forma continua. Voy transmutando a medida que los acontecimientos pasan y que los contextos se desarrollan en el transcurrir del tiempo. Esa transmutación, inevitable, también puede ser de alguna manera forzada por uno mismo cuando comienza a modificar su entorno. ¿La modificación del entorno es por el cambio en mí? Puede ser y no ser pues hay accidentes o actos de otros que también generan un cambio en uno mismo. Esto es medio como el cuento de la buena pipa. Lo importante, creo, es que no ocurra una transustanciación no deseada. Es decir que uno mismo no cambie en su sustancia si es que no es buscada. En esta obra hay una iluminación desde el contexto, como una desintegración de la falta de color, que va sacando la oscuridad. Hay una búsqueda de cambio, pero manteniendo vivo lo que sustancialmente es.',
    home: false,
  },
  {
    id: 24,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585289/Galeria%20R.P%20imagenes%20optimizadas/Solo_girones_uxcehm.png",
    title: "Solo girones",
    detail: "Mixto sobre papel, 45 x 30 cm.",
    think: 'De a poco se va deshaciendo. El viento, la luz, los colores, van entrando y van disolviendo aquello que los ocultaba. Si quiero, soy dragón, soy signo, soy hilos que desangran. Si lo intento me vuelvo amarillo, rojo, naranja, azul. Si empujo con todas mis fuerzas, hay luz, hay hojas, hay vida. Si sigo empujando se abre la puerta, se corre la tapa, se destraba la ventana y salgo. Poniendo un pie fuera ya estoy más lejos de la madera y la pólvora, de un rojo apagado, pero siempre expuesta a la explosión y al incendio. Mas lejos del olor a humedad, ácida, amarga, salobre. Mas lejos ya soy más luz sin la necesidad de ellos, sin la necesidad del dolor. Brillo, soy calor, soy flama viviendo, soy sol, soy lo que la vida me ha dado y no ellos. Salgo de la caja de fósforos.',
    home: true,
  },
  {
    id: 25,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585277/Galeria%20R.P%20imagenes%20optimizadas/Salir_del_domo_dj7eex.png",
    title: "Salir del domo",
    detail: "Mixto sobre papel, 45 x 30 cm.",
    think: '"¿Cuántos somos Truman?" me pregunté hace unas semanas atrás. No sé, tal vez no muchos, pero sí sé que yo soy un Truman. Pero Recién ahora estoy reconociendo los artefactos de luz que caían del cielo, las puertas de elevadores que daban a un falso cuarto, las personas que nombraban "objetos" de una forma muy marketinera. Recién ahora estoy pudiendo reconocer esas pistas que me decían que había algo raro. No me daba cuenta en ese momento pues era "feliz". Recuerdo los bailes con amigos imitando a Michael Jackson, las grabaciones con historias inventadas, las vacaciones en el mar o las montañas, todo era hermoso, felicidad, alegría, diversión. Pero, en un momento, todo se torna raro y empieza a habitar una incomodidad, una extrañeza. Muchos Trumanes que te acompañan empiezan a salir del domo, y no les importa la tormenta que les toca atravesar. Yo evalúo demasiado la tormenta y sigo en el domo. Tampoco me atrevo a preguntar. Hasta que un día, la naturaleza de ser Truman, despierta, sale de su cama, observa todo por última vez (quien sabe), con un desayuno liviano va hasta el puerto y sube a su velero... Y por si no nos vemos, buenos días, buenas tardes y buenas noches.',
    home: false,
  },
  {
    id: 26,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585277/Galeria%20R.P%20imagenes%20optimizadas/Jugando_con_la_muerte_lc78bo.png",
    title: "Jugando con la muerte",
    detail: "Mixto sobre papel, 30 x 45 cm.",
    think: 'No es algo que yo realmente sienta, en forma consciente, pero a través de mirar un poco mi vida y como me relaciono con algunos hechos, parece que sí es así. No es casual que hace unos días atrás escribiera acerca de la necesidad del cuidarse o ser cuidado. Montaña, mar, ruta, ciudad, en todos esos lados he tenido momentos cercanos a la muerte u ocurrieron eventos como posibilidad de encontrarme con la querida parca. Nada que me enorgullezca, nada que sea mérito, solo creo que es falta de atención y en algunos casos infortunio. Pero da como para pensar. La vida no es jugar con la muerte, la vida es la vida misma, jugar con la vida, donde se puede, diría, casi inevitablemente, encontrar con la muerte. Pero siempre la vida es una apuesta a la vida misma. Creo que puede ayudar tener conciencia del límite propio, de la finitud, de la fragilidad. Esta obra salió así, ¿será un mensaje de mi inconsciente? ¿Será que mi voz interior me habla desde la obra y me dice “ojo capo”? Todo para pensar y analizar con mi analista.Saludos. Buena apuesta a la vida de cada uno.',
    home: true,
  },
  {
    id: 27,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585262/Galeria%20R.P%20imagenes%20optimizadas/Ella_estaba_escondida_qsveyi.png",
    title: "Ella estaba escondida",
    detail: "Mixto sobre papel, 30 x 45 cm.",
    think: 'Las formas aparecen, eso ya lo he dicho varias veces y lo he experimentado otras tantas. Cuando empecé con este trabajo, las primeras manchas, ella ya estaba ahí, queriendo salir, queriendo mostrarse y queriendo decir "acá estoy", "esta soy yo", "esto que muestro es lo que digo", "no tengo otra forma de comunicarme que mostrándome". La mostración, la forma en la que salgo al mundo, para que me veas, para que veas. Nada está tan escondido que no se pueda ver, que no lo puedas ver. Siempre hay una forma en la que se asoma y se descubre, solo no se ve si no se le presta atención, si se trata de ignorar. Ella estaba escondida y salió de entre la mancha, pero como todo aquello que mancha la belleza, igualmente no la puede anular, destruir, no la puede convertir en lo mismo. Ella estaba escondida, ya no, ya la vimos, ya la vi. No hay forma, ahora, de no verla o de ignorarla. La belleza, la inocencia, la dulzura, la delicadeza, no se tapan con las manchas, siempre, pero siempre salen a la luz para ser descubiertas de nuevo, revaloradas y rescatadas.',
    home: false,
  },
  {
    id: 28,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585289/Galeria%20R.P%20imagenes%20optimizadas/Yo_te_cuido_qp9f5p.png",
    title: "Yo te cuido",
    detail: "Mixto sobre tela, 40 x 30 cm.",
    think: 'A pesar del caos en el que estamos sumidos, el de la vida misma, existe un pedido, una necesidad, en cada uno de nosotros de escuchar esta frase o solo de saber entenderla y comprenderla en el acto de otro o en el acto propio, yo te cuido. La necesidad de saber que hay alguien, en esta realidad de la modernidad líquida que habla Zygmunt Bauman, que te va a cuidar, que te va a contener. Siguiendo con la analogía de lo fluido de Bauman, encontrar un puerto donde siempre se te espera y que puede repararte de tanto daño que te provoca la constante objetivación de la sociedad, es necesario y vital. Pero no solo de ese daño, sino también algo más tangible, que es el daño que nos provocamos nosotros mismos por negar nuestros limites, por engañarnos frente a enfermedades más corpóreas, más concretas. Me surgen preguntas. Muchas. El yo cuido, puede ser un yo me cuido? ¿Un yo me cuido, me da la misma seguridad? ¿Me da la misma libertad? Yo te cuido, pareciera ser, la acción de dar la contención, el abrazo, para ayudar a entender, comprender, aceptar lo caótico de la vida. A esta altura me parece que uno no termina de entender la vida sin un otro.',
    home: false,
  },
  {
    id: 29,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585262/Galeria%20R.P%20imagenes%20optimizadas/Donde_busco_vkpnmj.png",
    title: "Donde busco",
    detail: "Mixto sobre tela, 40 x 30 cm.",
    think: 'Recuerdo un chiste algo tonto, de alguien que está buscando algo que perdió, viene otro y le pregunta que está buscando y dice "una moneda que perdí", entonces le preguntan "la perdió por aquí?", él dice "no más lejos", "¿y porque la busca aquí?", vuelven a preguntarle, y él contesta "porque acá hay más luz". Algo así era el chiste, pero a veces los chistes dicen más verdad de lo que parece. Buscar lo que se te perdió, en algún momento de la vida, puede estar en el lugar más oscuro de tu vida, entonces hay que ir a ese momento y buscar ahí. Con ayuda, seguro. Habrá dolores, seguro. Habrá tristezas, seguro. Habrá recuerdos que te hagan llorar, seguro. Pero es el lugar donde perdiste esa moneda que buscas, ese tesoro que necesitas recuperar. El recuperarlo o recuperarte vale más que todo lo oscuro que puedas ver, recordar, revivir. Recuperar el tesoro de lo que sos, reconocerte, revalorarte, vale todo lo que haya que bucear en lo hondo y oscuro. El resultado de encontrarte es Paz y Felicidad, con eso llega el Amor, así mismo por, sobre todo, y a los demás.',
    home: false,
  },
  {
    id: 30,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585289/Galeria%20R.P%20imagenes%20optimizadas/Ultimo_sue%C3%B1o_fwtjzm.png",
    title: "Ultimo sueño",
    detail: "Mixto sobre papel, 41 x 32 cm.",
    think: 'Un último sueño, en el ocaso? Se despierta y se termina. Formas y colores, etapas, momentos y un elefante a lo lejos, casi desvaneciéndose. Los sueños son raros. Habrá un nuevo despertar? Habrá nuevas formas y colores? Lejos de seguir pensando, solo atina a continuar, sin volver a preguntarse nada más. Ya desde hace un tiempo es un día a la vez. Una hora a la vez. Moverse y transcurrir de instante a instante. ¿Crear? ¿Qué cosa? Ya aprendió, el caos de la vida es como el caos de los sueños, no hay orden posible pero todo se va dando en un ir y venir de accidentes posibles. Nada es probable y sin embargo todo lo es y puede suceder. Habrá nuevas formas y colores? Se rehúsa a seguir pensando mientras busca con sus pies, que cuelgan de su cama, su calzado. Un día a la vez.',
    home: false,
  },
  {
    id: 31,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585263/Galeria%20R.P%20imagenes%20optimizadas/Antes_dudaba_ahora_no_se_xsznnn.png",
    title: "Antes dudaba, ahora no sé",
    detail: "Mixto sobre papel, 49 x 38 cm.",
    think: 'Es la primer obra realizada y terminada en mi nuevo lugar, que aún no ha sido inaugurado (aclaro porque muchos preguntan cuándo será la inauguración, no hay fecha). Siento, muy dentro mío que este espacio es como un refugio donde me encuentro yo conmigo mismo. Parece como una cuestión un tanto egoísta, bueno si, tal vez lo sea. Volví a la búsqueda de la estética del caos y la figuración sugerida por la mancha y el trazo. Dejarme llevar por lo que veo y me muestra ese movimiento cromático de la mancha y jugar, dejar salir ese homo ludens, pero más analógico. Y así como en las paredes de las calles, que muchas están escritas, intervenidas, en forma caótica, siguiendo criterios de distintos individuos, disfrutar de esa natural estética accidental. Que lleve ese título provisorio no es algo pensado en profundidad, solo es también dejarme llevar por lo que aparece. Podría llamarse "el amor es revolución", que también sería provisorio. Porque van apareciendo algunas cosas a medida que lo voy observando y dejando que descanse. Por tanto, el titulo final, así como lo que escribo, puede llegar a ser otro e inesperado, como el encuentro con un acontecimiento.',
    home: false,
  },
  {
    id: 32,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585277/Galeria%20R.P%20imagenes%20optimizadas/Persiguiendo_una_fantasia_ms20ns.png",
    title: "Persiguiendo una fantasía",
    detail: "Mixto sobre papel, 49 x 38 cm.",
    think: 'Persiguiendo una fantasía encontré la realidad de lo que soy. Mas duro de lo que pensé. Mas doloroso de lo que imaginé. Mas triste de lo que creí. Mas angustiante de lo que viví. Es un paso grande e importante. Oh! Fantasía mía que me trajiste hasta acá. Lo que he encontrado no lo esperaba. Pero me has puesto sobre la realidad de lo que soy. Para empezar a disfrutar lo que tengo y lo que hay dentro de mi corazón y de mi alma. Me has abierto los ojos. Me has puesto sobre la tierra. Y la gravedad se siente, no solo en mis pies, sino en todo mi cuerpo. Hoy necesito el abrazo que contenga, la caricia que calme, la palabra que salve, la mirada que entienda, la mano que me acompañe. Hoy necesito la compañía que celebre conmigo la alegría de los encuentros con mis amores, de nuevos lugares o los de siempre, no importa. Porque no es un nuevo camino, es el mismo, pero se ve distinto. Se siente distinto. Oh! Fantasía mía que me has traído hasta aquí y hasta hoy. Te agradezco todo lo vivido y construido al seguirte. Oh! Fantasía mía que me hiciste conocer el amor que me seguirá de por vida. Hay un anhelo y hay una esperanza.',
    home: false,
  },
  {
    id: 33,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585262/Galeria%20R.P%20imagenes%20optimizadas/El_principio_de_invisibilidad_vmjgez.png",
    title: "El principio de invisibilidad",
    detail: "Mixto sobre papel, 50 x 45 cm.",
    think: 'Hay un super poder maravilloso y es el ser invisible o hacerse invisible según la propia necesidad. ¡¡Es fantástico!! Hay momentos que uno desea no verse y con este super poder mutas en un ser totalmente inexistente, nadie te ve, nadie te percibe, ¡nadie sabes que estás! Maravilloso. Yo a través de los años he ido mejorando y desarrollando ese don, hasta sorprenderme a mí mismo cuando lo uso. Puede estar el lugar atestado de gente y de repente, como por arte de magia, o como si me pusiera el anillo Único, desaparezco, puedo ver a todos, pero nadie a mí. Algunos que poseen ese don no están felices como yo, porque además de ese don tienen una necesidad importante de ser vistos y reconocidos por los demás, entonces protestan, se enojan, buscan pelea, denostan a los demás buscando sobre salir. Es una lástima porque no saben lo que se pierden. El ser invisible o poder hacerte invisible a voluntad, te da justamente esa libertad hermosa de no ser visto. Lo mío empezó hace mucho tiempo, en mi infancia, ahí pude ver que para algunas personas no existía, no entendía bien como era la cosa ni los porqués peeeero ya me iba dando cuenta. En mi adolescencia y en la secundaria más aún. Y pude ya hacer uso de ese don, le empecé a agarrar el gusto y le encontré la utilidad, por ejemplo, en las rateadas. Si yo me rateaba, nadie se daba cuenta y aunque no estuviera en clase, ya tenía el presente y con eso zafaba. Debo reconocer que como todo adolescente me excedí y me ratié aun cuando no estaba en modo "invisible" y necesité de la reincorporación en el colegio. Ya de adulto lo puse en práctica en muchos lugares, como por ejemplo el supermercado. Cuando podía detectar que había alguien con quien no quería encontrarme, ahí nomas daban un giro a mi carrito de compras, y detrás de otra góndola desaparecía. Y así evitaba encuentros con personas que no eran de mi agrado. Hoy soy un "Yedi" en esta habilidad increíble y lo digo humildemente.',
    home: false,
  },
  {
    id: 34,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585277/Galeria%20R.P%20imagenes%20optimizadas/Mascara_de_contemplar_mgg2eg.png",
    title: "Máscara de contemplar",
    detail: "Mixto sobre papel, 32 x 24 cm.",
    think: 'Jugar un rato no hace mal a nadie. Te hace olvidar algunos momentos no tan simpáticos de la vida. No te quedas enganchado y podés poner la energía en algo más divertido que es justamente el jugar. Sigo creyendo que el juego es lo más educativo en la vida y jugar creando es como el punto más alto de esa cuestión educativa. Recién leía a Benjamin acerca de la reproductibilidad de la obra de arte, pintura, música, films, fotos, etc., obras de arte, y me quedé pensando que la obra de arte es irreproducible, pues pierde en su reproducción lo que hace ser una obra de arte. Una reproducción no te moviliza como el original, no produce lo mismo que un original. Benjamin habla del aura de la obra de arte, como que con las reproducciones va perdiendo esa aura. Pero no es que pierde el aura por la repetición de sí misma, porque no es ella misma, la obra no es la repetición, parece una obviedad, pero no lo es. La forma de su creación, el proceso, el creativo, la materia misma, todo en sí la hace ser original y con su aura propia que te mueve de una forma que solo esa obra logra en vos que sos el observador. Pensaba luego en la contemplación, el estar en silencio en contacto a través de los sentidos con esa obra original, que puede incluso ser un paisaje.',
    home: false,
  },
  {
    id: 35,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585263/Galeria%20R.P%20imagenes%20optimizadas/El_juego_del_caos_zziyj9.png",
    title: "El juego del caos",
    detail: "Mixto sobre tela, 120 x 70 cm.",
    think: 'Eterno caos, creador de posibilidades inexactas, incoherentes con la pretensión humana. Posibilidades inclusive caóticas en su esencia, pues del caos nace más caos. Interminables y eternas como su gestor. Aunque parecen haberse perdido en el tiempo estas vuelven, pero en distintos tiempos y en distintos seres humanos. Guay de aquel que sufriera en su tiempo vital el encuentro en más de una oportunidad con una misma posibilidad caótica. No llegaría a ser testigo de tremendo suceso. Es hoy cuando debe suceder y no mañana el encuentro con esa posibilidad extraña que se te pone de frente. Este trabajo aún no está terminado, pues he encontrado que se podrían unir algunas posibilidades caóticas, generando una ilusión de conexiones entre ellas, pero no obstante eso siguen apareciendo más y más situaciones inconexas.',
    home: false,
  },
  {
    id: 36,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585289/Galeria%20R.P%20imagenes%20optimizadas/Un_lugar_donde_so%C3%B1ar_bien_ktpf7k.png",
    title: "Un lugar donde soñar bien",
    detail: "Dibujo en papel con tinta china, 45 x 30 cm.",
    think: 'Algunos sueños son complicados, surrealistas, no llegan a pesadilla, pero son bizarros. Divertido jugar con las líneas y ver los personajes que salen y empiezan a cobrar vida. A veces los sueños son raros porque raro es el lugar, o extraño, en donde se duerme, creo que muestran el caos de pensamientos que te vienen mientras intentas conciliar el sueño. Y que cueste también es directamente proporcional a la rareza o extrañeza del lugar donde dormís y muchas veces es el lugar de siempre, pero ¿por qué se vuelve extraño? ¿Que lo vuelve extraño? ¿Será el tiempo que vivimos? ¿Será la soledad en la que vivimos? ¿Será que uno se vuelve extraño de sí mismo? ¡¡¡¡¡Que trabajo tendrá mi psicólogo!!!!!',
    home: false,
  },
  {
    id: 37,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585289/Galeria%20R.P%20imagenes%20optimizadas/Una_sirena_me_sigue_de_cerca_xgl8yj.png",
    title: "Una sirena me sigue de cerca",
    detail: "Mixto sobre papel, 30 x 45 cm.",
    think: 'Daryl Hannah, Tom Hanks, saben de lo que hablo en este trabajo. Creo que en el momento que vi esa peli comencé a ser seguido, casi acosado, por esta sirena. La encuentro a todos lados donde voy, en el mar de Rocha, en los lagos del sur, en los bosques de la cordillera (si es raro, pero está), en una esquina de Palermo, en el río de mi ciudad. Ahí está siempre, me sonríe, me mira con sus ojos enamorados. Sus cabellos hermosos y rubios, dorados por el sol, se mueven en slow motion por el viento suave. ¿Y yo? Yo soy solo un tipo que la ve y no puede acceder a ella, un tipo no digno de tanta belleza y misterio. A veces creo que nunca podré tocar su piel y ver de cerca sus labios. Tal vez solo sea un sueño.... pero quiero seguir soñándola entonces!!!',
    home: false,
  },
  {
    id: 38,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585262/Galeria%20R.P%20imagenes%20optimizadas/Definido_en_paz_pqjp5l.png",
    title: "Definido en paz",
    detail: "Mixto sobre tela, 100 x 80 cm.",
    think: 'Lo empecé pensando en otro trabajo anterior, buscando darle una suavidad en las transparencias, pero como siempre me puse a jugar y a disfrutar de lo que va apareciendo entre lo lúdico y lo placentero, entre lo alegre y lo inocente. Incursionando en detalles, pequeñas cosas que dan como un volumen de sensaciones y placeres de ver y disfrutar lo que aparece. Seguir jugando y encontrarte al final con lo más profundo de lo que hay en tu corazón. ¿¡Es como estar en la intimidad con quien se ama, no!?',
    home: false,
  },
  {
    id: 39,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585278/Galeria%20R.P%20imagenes%20optimizadas/Levantate_y_anda_wtutt1.png",
    title: "Levantate y anda",
    detail: "Mixto sobre tela, 60 x 80 cm.",
    think: 'Cuando realice esta obra fue un momento en el que la actualidad nacional mostraba una impunidad obscena. Las ideologías son religiones y las religiones ideologías. Todas las ideologías siempre dejan afuera una parte importante de la humanidad o de lo que nos hace realmente humanos. Cuando una ideología política hace presión para cumplir con sus objetivos siempre pisa o atropella a las personas, cercenando sus derechos de seres humanos. En momentos de mayor necesidad de la sociedad, la ideología pisa y destruye a la sociedad misma y su necesidad más básicas y primarias. Se pone en juego el cinismo y la obscenidad del poder.',
    home: false,
  },
  {
    id: 40,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585289/Galeria%20R.P%20imagenes%20optimizadas/Una_forma_que_amenaza_s40z22.png",
    title: "Una forma que amenaza",
    detail: "Mixto sobre papel, 47 x 38 cm.",
    think: '',
    home: false,
  },
  {
    id: 41,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585289/Galeria%20R.P%20imagenes%20optimizadas/Si_soy_timido_bg4ivw.png",
    title: "Si, soy tímido",
    detail: "Mixto sobre tela, 90 x 60 cm.",
    think: 'Mostrarme nunca ha sido mi fuerte, aunque reconozco que de alguna manera u otra me han sabido individualizar. Eso me ha resultado siempre un peso. A veces quisiera no ser visto, pero no lo logro muy a menudo. ¿será mi personalidad? No lo sé. Solo sé que es muy difícil para mí mostrarme.',
    home: false,
  },
  {
    id: 42,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585290/Galeria%20R.P%20imagenes%20optimizadas/Tomar_el_camino_simple_eegxhw.png",
    title: "Tomar el camino simple",
    detail: "Mixto sobre tela, 90 x 60 cm.",
    think: 'Una obra realizada con acrílico, sintético al agua y liquid paper. Tomar el camino simple nunca fue una verdadera opción para mí, siempre voy por los mas rebuscados. Es la búsqueda que me lleva a hurgar por donde tal vez no deba, pero es una búsqueda al fin. Cuando pinto por lo general busco mucho entrar en el caos de las formas, trazos, colores, manchas. Eso me pone frente a un hermoso panorama de diversas posibilidades con diversos finales. Esta vez tome por el camino de la simpleza de algunas formas y colores más planos.',
    home: false,
  },
  {
    id: 43,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585278/Galeria%20R.P%20imagenes%20optimizadas/Mas_facil_por_lo_simple_iptxsf.png",
    title: "Mas fácil por lo simple",
    detail: "Mixto sobre papel, 50 x 35 cm.",
    think: 'Busque la mancha, busque ver que me presentaba. Como en ese momento había demasiada confusión en todos lados, pensé en no complicarme mas de lo que me complicaba la vida misma y solo sentí la necesidad de simplificar las formas. Encontré una rápida calma y alegría.',
    home: false,
  },
  {
    id: 44,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585277/Galeria%20R.P%20imagenes%20optimizadas/Monocromia_del_contagio_c2ffen.png",
    title: "Monocromía del contagio",
    detail: "Mixto sobre cartón entelado, 50 x 70 cm.",
    think: 'Plena pandemia, se pintaba en lo que encontraba. Los miedos, los monstruos de la duda y la ignorancia, el sentido de fragilidad. La vida que pende de un hilo. Todo eso causaba mucha angustia y los monstruos de la depresión siempre asomaban.',
    home: false,
  },
  {
    id: 45,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585263/Galeria%20R.P%20imagenes%20optimizadas/Hombre_y_pajaro_wrctfc.png",
    title: "Hombre y pájaro",
    detail: "Mixto sobre papel.",
    think: 'Una obra que me encanta, porque me ha dejado vislumbrar lo maravilloso que trae el caos, de la mancha y de los trazos. Siempre hay que estar atento a lo que trae la marea, en este caso del caos. Chuck Nolan el personaje de castaway esperaba lo que le traía el mar para poder salir de esa isla desolada. El caos, como la marea, siempre te trae algo maravilloso.',
    home: false,
  },
  {
    id: 46,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585264/Galeria%20R.P%20imagenes%20optimizadas/Dale_las_vueltas_que_quieras_vhlnsp.png",
    title: "Dale las vueltas que quieras",
    detail: "Mixto sobre tela, 60 x 90 cm.",
    think: 'Año 2020, pandemia, primeros días, primeras semanas. El encuentro con la fragilidad de la vida por donde miraras. Dale las vueltas que quieras, no solo te invita a dar vueltas a la obra para observarla, sino que también te invita a que por mas vueltas que le des, la vida es frágil y vivimos pendiendo de un hilo. Tal es así que un minúsculo virus podía con la vida del mas grande y poderoso de los seres humanos. Dale las vueltas que quieras te dice que no somos inmortales. Te dice que la vida que tenes la aproveches en vivirla con la intensidad del amor, de la paz, de la armonía, del hacer las cosas bien y del compartirla con los amores que nos han sido dados.',
    home: false,
  },
  {
    id: 47,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585277/Galeria%20R.P%20imagenes%20optimizadas/La_del_barco_nm5e8h.png",
    title: "La del barco",
    detail: "Mixto sobre papel, 35 x 50 cm.",
    think: 'La del Barco, hace alusión a la playa “del barco” en el balneario de “La Pedrera” en Rocha, Uruguay. Donde veraneo desde el 2009, donde encuentro los momentos de mayor relax, de descanso, donde cargo mis baterías y donde, creo, la vida se me hace mas maravillosa que de costumbre.',
    home: false,
  },
  {
    id: 48,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585277/Galeria%20R.P%20imagenes%20optimizadas/Para_aterrizar_en_mi_mundo_hdjqme.png",
    title: "Para aterrizar en mi mundo",
    detail: "Mixto sobre papel, 35 x 50 cm.",
    think: 'Este es un mapa de vuelo, que dejo para que todo aquel que quiera entrar en mi mundo, lo siga y me encuentre. En mi mundo soy como un náufrago, pero sin la preocupación de que alguien me encuentre.',
    home: false,
  },
  {
    id: 49,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585277/Galeria%20R.P%20imagenes%20optimizadas/Paisaje_de_mujer_hwnln2.png",
    title: "Paisaje de mujer",
    detail: "Mixto sobre tela, 70 x 90 cm.",
    think: 'Una mujer desnuda en la ciudad. Una mujer vulnerable en la ciudad. Una mujer frágil en la sociedad. Vuelve la mancha a proponer una figuración posible, pero solo es posible ser descubierta por la mirada del autor, que con su inconsciente a maquina completa, mira, observa y define. La vulnerabilidad, la fragilidad y la desnudez de la mujer solo es una cuestión de la actitud del resto de la sociedad que juzga y desde una moral dudosa e inhumana.',
    home: false,
  },
  {
    id: 50,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1691585263/Galeria%20R.P%20imagenes%20optimizadas/Hieroticum_himhx3.png",
    title: "Hieroticum",
    detail: "Sintético sobre tela, 70 x 90 cm.",
    think: 'Formas que van y vienen, trazos que las unen. Despiertan en algunos observadores formas casi eróticas. Pero por otro lado hay algo muy quieto, e inexpresivo, como pocos rasgos expresionistas. Hay algo en esas formas algo orgánicas y eróticas que no las dejan ser del todo. Algo hermético y religioso que no permiten que se desarrollen en total libertad expresiva y sensual.',
    home: false,
  },
]