export const paintings = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1688580712/Galeria/4_mybtpx.jpg",
    title: "Yo te cuido",
    detail: "Mixto sobre papel, 41x32 cm.",
    home: true,
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1688580712/Galeria/24_vsmhlb.jpg",
    title: "Yo te cuido",
    detail: "Mixto sobre papel, 41x32 cm.",
    home: true,
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1688580711/Galeria/25_fbeauu.jpg",
    title: "Yo te cuido",
    detail: "Mixto sobre papel, 41x32 cm.",
    home: false,
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1688580711/Galeria/8_cyj8j3.jpg",
    title: "Yo te cuido",
    detail: "Mixto sobre papel, 41x32 cm.",
    home: true,
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1688586340/Galeria/19_jbq9au.jpg",
    title: "Yo te cuido",
    detail: "Mixto sobre papel, 41x32 cm.",
    home: true,
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1688580705/Galeria/29_bbb5lh.jpg",
    title: "Yo te cuido",
    detail: "Mixto sobre papel, 41x32 cm.",
    home: false,
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1688581877/Galeria/El_a%C3%B1o_del_Gato_sin_alusion_alguna_acrilico_sobre_tela_y_sintetico_liquid_podria_haber_puesto_mixta_60_x_90_cm.-34_pi5lgh.jpg",
    title: "El año del gato sin alusión alguna",
    detail: "Mixto sobre tela, 60 x 90 cm.",
    home: true,
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1688580707/Galeria/30_dwfqt8.jpg",
    title: "El año del gato sin alusión alguna",
    detail: "Mixto sobre tela, 60 x 90 cm.",
    home: false,
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689102400/Galeria/elsue%C3%B1odeclara-35_chnp41.jpg",
    title: "El sueño de Clara",
    detail: "Mixto sobre tela, 60 x 90 cm.",
    home: false,
  },
  {
    id: 10,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689102402/Galeria/21_r9vel9.jpg",
    title: "Volar no es sueño",
    detail: "Mixto sobre tela, 60 x 90 cm.",
    home: false,
  },
  {
    id: 11,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689102399/Galeria/N_4-2020Dale_las_vueltas_que_quieras_mixto_sobre_tela_60_x_90_cm-39_grl4fn.jpg",
    title: "Dale las vueltas que quieras",
    detail: "Mixto sobre tela, 60 x 90 cm.",
    home: false,
  },
  {
    id: 12,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689102399/Galeria/N_25-2020levantateyandamixtosobretela60x80-40_ejsxkj.jpg",
    title: "Levantate y anda",
    detail: "Mixto sobre tela, 60 x 90 cm.",
    home: false,
  },
  {
    id: 13,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689102398/Galeria/37_moauvt.jpg",
    title: "Levantate y anda",
    detail: "Mixto sobre tela, 60 x 90 cm.",
    home: false,
  },
  {
    id: 14,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689104933/Galeria/DefinidoenPaz-mixtosobretela-80x100cm-33_i2m3mn.jpg",
    title: "Definido en paz",
    detail: "Mixto sobre tela, 80 x 100 cm.",
    home: false,
  },
  {
    id: 15,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689104932/Galeria/26_ryrgx2.jpg",
    title: "...",
    detail: "Mixto sobre tela, 80 x 100 cm.",
    home: false,
  },
  {
    id: 16,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689104929/Galeria/38_veksfp.jpg",
    title: "...",
    detail: "Mixto sobre tela, 80 x 100 cm.",
    home: false,
  },
  {
    id: 17,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689104927/Galeria/ClaraenunminutoRexo-31_spitq3.jpg",
    title: "Clara en un minuto",
    detail: "Mixto sobre tela, 80 x 100 cm.",
    home: false,
  },
  {
    id: 18,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689104925/Galeria/2020Escapemixtosobremdf35x55cm-18_uyhxeo.jpg",
    title: "Escape",
    detail: "Mixto sobre tela, 35 x 55 cm.",
    home: false,
  },
  {
    id: 19,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689104924/Galeria/36_vpxlab.jpg",
    title: "La codicia humana",
    detail: "Mixto sobre tela, 35 x 55 cm.",
    home: false,
  },
  {
    id: 20,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689105717/Galeria/27-min_svedwe.jpg",
    title: "...",
    detail: "Mixto sobre tela, 35 x 55 cm.",
    home: false,
  },
  {
    id: 21,
    img: "https://res.cloudinary.com/dn6w1lstv/image/upload/v1689105839/Galeria/09_ykq1ht.jpg",
    title: "...",
    detail: "Mixto sobre tela, 35 x 55 cm.",
    home: true,
  },
];
